### ISSUE TITLE
Styling for hero text

### ISSUE THREAD

**Issue by SkySails** [SkySails/hirewd#1]
The current hero text fits the size of the page pretty well. The new text, provided below, is quite a lot longer and such do not fit with the same set of styles. We need to think of another structure/design.

```
Does your business need a website?
Do you have an IT-project that needs a helping hand?
Hire web developers in training!
Dive deep into a market full of aspiring web designers and engineers, eager to assist you in the process of realising your dreams.
```

**Comment by moh3ni** [comment]
I think it is too much text in hero section, should be much less.

**Comment by SkySails** [comment]
Feel free to boil it down! The text in the original design was the following:
```
Students.
Web developers.
Cheap websites.
```

**Comment by moh3ni** [comment]
something like this:
`Need a website?
hire web developers in training!
`
or the original one.

**Comment by Fijo-Lurk** [comment]
Here are some inspiration that i added to the design. they are a bit cheesy but feel free to add the text to the design and see how it looks [https://imgur.com/a/dIfOzhm](url)
I agree that the text should be short so that there is not too much information on the landing section.

**Comment by hannesqvarnstrom** [comment]
The idea while writing the copy was that not all of it is the hero! :) some of it can be put elsewhere, like a further description or a sub-text. I like @Fijo-Lurk 's proposal. 
I do think it's important to have sufficient information on the landing page, since the scope of the website is rather wide.

**Comment by hannesqvarnstrom** [comment]
One idea for changing the copy is removing the colourful language as such:

Need a website?
Hire web developers in training!
Dive in and start realising your dreams. [Get started] [Read more]

**Comment by SkySails** [comment]
That *sounds* great, but the "Hire web developers in training" sentence is also quite long. That on its own isn't a problem, as long as the design (or more precise, the *typography*) is adapted to the change. Do you have an idea on how to accommodate for this?

**Comment by hannesqvarnstrom** [comment]
I see the problem, good thinking! :) 
I'm a big fan of changing the text so that the typography doesn't need too much work.
What about:
-same-
Hire a student!
-same-

**Comment by SkySails** [comment]
Absolut! Det är kort och koncist. Det kan nog löna sig att ändra lite `font-size`-regler ändå, men det är helt klart ett steg i rätt riktning!

**Comment by hannesqvarnstrom** [comment]
Sure, I still haven't been able to load the index.js with styles in a live-server though. Maybe I'm missing some extensions?

**Comment by SkySails** [comment]
You need to install nodejs, there is a complete set of instructions in the readme! In short:

1. Install [NodeJS](https://nodejs.org/dist/v12.18.4/node-v12.18.4-x64.msi)
2. Clone this repo and open it in VSCode
3. Open a new terminal (`Ctrl + Shift + Ö`) and type `npm run dev`
