### ISSUE TITLE
Responsive styling for hero image

### ISSUE THREAD

**Issue by SkySails** [SkySails/hirewd#2]
The hero image is constructed using SVG. This enables the image to be resized in any way, up to any size without losing any details. However, using an image as blocking content like this instead of using a hero-wide background image requires a lot of creativity when it comes to responsiveness! Should the image disappear when the screen shrinks past a certain limit? Or should the `flex-direction` be changed into a column layout so that the text gets stacked on top of the image?

**Comment by Fijo-Lurk** [comment]
I would think it would be nicer if we change it to flex-direction column. I think the whole of the page you have designed is very good so we could start coding it then test what it would look like to delete the image completely or move it to column.
