### ISSUE TITLE
Intro section

### ISSUE THREAD

**Issue by SkySails** [SkySails/hirewd#4]
We need a section with information about the initiative and goal. An idea would be to use some of that copy-text together with illustrations in a compelling, user-friendly way!

- [x] Brainstorming / Prototyping
- [x] Design
- [ ] Code

**Comment by Fijo-Lurk** [comment]
@hannesqvarnstrom The text you wrote I think is a good start to such a section.

> HireWD is a community driven portal, designed to match clients up with competent and attentive student-level developers.
Previously, when a developer got asked about a project that they don't have the time for, they'd decline.
By deferring the project to HireWD, now everyone who needs a site built can get it done!

**Comment by Fijo-Lurk** [comment]
<img width="365" alt="Skärmavbild 2020-10-05 kl  18 41 58" src="https://user-images.githubusercontent.com/70694476/95107770-a30d7d80-073a-11eb-9ac7-8e487648b15e.png">
Where did you get your SVG on the landing page from? @SkySails

**Comment by SkySails** [comment]
I got them from drawkit.io

**Comment by Fijo-Lurk** [comment]
<img width="607" alt="Skärmavbild 2020-10-06 kl  09 20 33" src="https://user-images.githubusercontent.com/70694476/95170756-3be0df00-07b5-11eb-8e80-757243709c39.png">

some prototypes.

**Comment by hannesqvarnstrom** [comment]
I like Desktop 3! I also like the man with the cap, it looks like you @SkySails 😄

**Comment by Fijo-Lurk** [comment]
<img width="680" alt="Skärmavbild 2020-10-06 kl  11 01 16" src="https://user-images.githubusercontent.com/70694476/95181206-4ace8e00-07c3-11eb-8126-e347773b92c7.png">
do you have any thoughts on how to improve the contrast on slider two where the green background and white text merge a bit?

**Comment by hannesqvarnstrom** [comment]
Darkening the green would increase contrast.

**Comment by Fijo-Lurk** [comment]
![Uploading Skärmavbild 2020-10-06 kl. 11.11.09.png…]()

**Comment by hannesqvarnstrom** [comment]
Much better! I want to fix the copy too, it's too many words and too inconcise. That way we can increase the font-size and make it more readable, and less reading-intense.

**Comment by hannesqvarnstrom** [comment]
I'm thinking - how about splitting the text up a bit? We can have one page/section with a short description and one page/section with a more verbose description. Like this:

_(Short Description/Intro:)_
**HireWD is a community driven portal, designed to match clients up with competent and attentive student-level developers.
By deferring projects and requests to HireWD, everyone can get their websites built.**
_(This part can be styled like the one we agreed on previously, with coloured boxes. The text can be larger due to less word-count over-all.)_


_(Lengthier section:)_
**The level of competence in the world of IT is always rising, and the skill levels of students are always getting better.
Working developers often don't have the time to meet the demands from the market, which gave us this idea.
Let's invite students to take on the projects that no one else can take.
We can share the workload evenly, giving those with free time the opportunity to work extra in the field they're studying.**

**Comment by SkySails** [comment]
@Fijo-Lurk Looks good! However, keep in mind that not everyone is using a monitor with a 16:9 ratio. The current design has a `max-width` container to keep the content centered when the screen becomes wide (currently, the content never gets wider than 1230px), what happens to those colored sections in your design when the screen becomes wider than the content? Do they just get cut off? Do they extend all the way out to the edge of the screen?

**Comment by Fijo-Lurk** [comment]
That was a good reminder. I had not thought of that when I designed. They could end after X width, as in the picture.
<img width="612" alt="Skärmavbild 2020-10-06 kl  11 55 28" src="https://user-images.githubusercontent.com/70694476/95187631-aac93280-07cb-11eb-807a-7f0f4dc0a4b7.png">
or something like the second image and put a max-width on it. problems with it become when you go down in size. But you could remove the illustration after X width
<img width="650" alt="Skärmavbild 2020-10-06 kl  12 01 52" src="https://user-images.githubusercontent.com/70694476/95187929-0bf10600-07cc-11eb-90a6-baca3e678e50.png">

**Comment by SkySails** [comment]
Looking good! Took some inspiration and created a design proposal that keeps the overall look of the original!

![Proposal](https://user-images.githubusercontent.com/46646495/95207752-7ca61b80-07e8-11eb-9143-ee44077eebba.png)

**Comment by hannesqvarnstrom** [comment]
GREAT job! You nailed the idea that was in our minds, I think! 😄 Maybe it's time to close this issue then, and brainstorm the actual website?

**Comment by Fijo-Lurk** [comment]
well done, looks really good and cohesive👍🏻

**Comment by SkySails** [comment]
@hannesqvarnstrom Thank you! I hope so as well. I have some alternate designs as well, I'll have to finish them first before I feel comfortable with ultimately deciding on a design! There's nothing preventing us from brainstorming the dashboard already though, feel free to open a new issue and give it a try!

@Fijo-Lurk Thank you! I used your designs as inspiration!
