### ISSUE TITLE
fix boxshadow on sign up button

### ISSUE THREAD

**Issue by hannesqvarnstrom** [SkySails/hirewd#6]
or rather, is that box-shadow intended? it's rather large and spread out.
the class isn't in the style documents.

**Comment by SkySails** [comment]
Well yes, it is intended and is part of the `<Button>` component that is the only thing left from the site's previous JSX (Javascript + HTML) state. The box-shadow might seem off, but it is a design trend! Did you notice that there is a similar box-shadow around the call-top-action button (The one that says "Get started")? It's subtle but actually changes the overall feeling a bit! I am open to getting rid of it in case everyone is agains it of course!

**Comment by hannesqvarnstrom** [comment]
Yes, the 'Get Started' one is dank! 👍 Very cool without any spread, but the 'Sign Up' button's shadow isn't in the same style. Can we make them similar?

**Comment by SkySails** [comment]
Hmm. The styles for both buttons, in terms of box-shadow at least, is exactly the same except for the color. I think the reason why the Signup-button's box-shadow seems more wide-spread is its darker color! I'll reduce the opacity a bit more and see what the result gives.

**Comment by SkySails** [comment]
Please check the [latest development preview](https://hirewd-e3arwoi6r.vercel.app/) for the result!

**Comment by hannesqvarnstrom** [comment]
I think that it's fine for now, maybe we can discuss at some other time. Not hugely important.
